on:
  push:
    branches:
      - master
  pull_request:

name: Linter
jobs:
  format:
      name: Format
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.24.x'
          channel: 'beta'
      - name: Check formattting
        run: |
          if find . -name *.dart -not -path "./lib/generated/*" -exec flutter format --set-exit-if-changed --dry-run {} +
          then
            echo "The code formatting is nice and tidy."
          else
            echo "Please fix the formatting of the files listed above."
            exit 1
          fi

  analysis:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.24.x'
          channel: 'beta'
      - name: Install dependencies
        run: flutter pub get
      - name: Run linter
        run: flutter analyze
